### PR TITLE
Add Nim ports of the official C GLFW examples

### PR DESCRIPTION
**Pull request by johnnovak**
* particles.nim coming soon too...

### CODE REVIEW

**Comment by ephja** [comment]
Are you aware of the official OpenGL interface? Is it missing something?

Have you tested the examples on a recent Nim revision? It now fails with this and a few other errors:
```
/home/exe/.nimble/pkgs/glm-0.1.1/glm/mat.nim(17, 18) template/generic instantiation from here
lib/core/macros.nim(321, 45) Error: type mismatch: got (Array constructor[0..1, Vec2[system.float]]) but expected 'Mat2x2 = CompositeTypeClass'
```

Other than that it looks good.

**Comment by johnnovak** [comment]
I tried the "official" OpenGL interface first, but couldn't get any of the example code to run on any OS (tried OS X, Windows and Linux, all resulted in a segfault). I also had problems passing the address of `getProcAddress` to `gladLoadGL` when I tried to use it with glfw (I think it always wanted to do it's own loading).

So then I found glad and I think it's the superior solution because with it you can generate bindings for a specific OpenGL version and extensions you're targeting. It uses the official OpenGL specs to generate the bindings automatically, so it's a superior solution to the static official interface, which has to be maintained by hand. By the way, I added Nim support to glad myself.

Regarding the glm errors, that's interesting. I submitted a few patches to nim-glm that fixed a few similar errors for Nim 0.13.0.

Are you using Nim 0.13.0 or the latest development version? Also, could you please update your nim-glm and try again? I'll have a look if the error still persists.

**Comment by johnnovak** [comment]
Oh, and another reason is that I think the end-user of a library should be able to build and run the examples with a few simple commands, otherwise most people won't just bother. Except for the glm error you mentioned (which I will fix), now it's easy to do that by just installing nim-glfw and nim-glm with Nimble and off you go! As I said, that just didn't work with the official wrapper out of the box, and I couldn't be bothered to investigate/fix it, because I think the static manually maintained interface approach is an inferior solution...

**Comment by ephja** [comment]
Ok that's fine for now. I'm using a development version.

The loading mechanism for the opengl library is fine, as long as you don't need conditional loading, which it should support at some point. The examples can be ported some other time, if necessary.

A package could be created for the examples, which would make it trivial to install the dependencies.

**Comment by johnnovak** [comment]
Ok, so are you expecting me to do anything else on this PR or is it good to go? I'm a bit reluctant to start debugging glm with the dev version of Nim as things seem to be quite a bit in flux now...

**Comment by ephja** [comment]
People tend to rely on development versions since 1.0 hasn't been released yet. It's time-consuming, but difficult to avoid. Maybe a branch could be introduced for devel compatibility, but I don't see a way to specify a dependency that refers to a specific branch.

Thanks!

**Comment by johnnovak** [comment]
Ok I think I'll start using the dev branch too then and submit a patch to nim-glm when I'll have some time. Btw, thanks for nim-glfw, it's great and I like the succinctness of the API!

**Comment by ephja** [comment]
@johnnovak No problem! Good to know.

I wonder what people think about the "win" abbreviation though. It hardly saves much typing.

**Comment by johnnovak** [comment]
I personally like it, together with the rest (e.g. `mouseBtnCb`, `cursorPosCb`). It's clear what it means from the context, and the terseness is refreshing after 8+ years of professional Java coding :)

**Comment by ephja** [comment]
Ok. Yeah I'm sure it is :stuck_out_tongue:

**Comment by johnnovak** [comment]
FYI, I've submitted a fix to nim-glm, so the examples will compile fine with the dev version of Nim if you fetched the latest glm version.

**Pull request merged**
